name: R-CMD-check
on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: macOS-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install remotes package
        run: Rscript -e 'install.packages("remotes")'
      - uses: r-lib/actions/check-r-package@v2
