name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install package dependencies
        run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
