name: R-CMD-check
on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: macOS-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v3
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_cran("rcmdcheck")
      - uses: r-lib/actions/check-r-package@v2
