name: R-CMD-check
on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: macOS-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Set up R environment
      - uses: r-lib/actions/setup-r@v2

      # Install system dependencies for R packages
      - name: Install System Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      # Install remotes package
      - name: Install remotes
        run: |
          install.packages("remotes")

      # Install package dependencies
      - name: Install Dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)

      # Run R CMD check
      - uses: r-lib/actions/check-r-package@v2
